import '../App.css';
import classnames from 'classnames';
import DrawerButton from '../components/DrawerButton';
import Circle from './Circle';
import CircleImage from './CircleImage';
import React,{ useState,useEffect } from 'react';
import axios from 'axios';
import { useNavigate } from "react-router-dom";
import secureLocalStorage from 'react-secure-storage';
import ModeTitle from './ModeTitle';